blog/views/authorization.py
from flask import Blueprint
from flask_login import login_user, logout_user
from flask_login import login_required, current_user
from blog.forms import login_form
from blog.models import Admin
from flask import render_template
from flask import flash, redirect, url_for
from blog.views.management import redirect_to_last_page

authorization_buleprint = Blueprint('authorization', __name__)

@authorization_buleprint.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect_to_last_page()
    form = login_form()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember = form.remember.data

        administrator = Admin.query.first()
        if administrator:
            if username == administrator.username and administrator.check_password(password):
                login_user(administrator, remember) 
                flash('This is your home!', 'success') 
                return redirect_to_last_page()
            flash('username or/and password is/are wrong!', 'warning')
        else:
            flash('No administrator now', 'warning')
    return render_template('authorization/login.html', form=form)

@authorization_buleprint.route('/logout')
def logout():
    logout_user()
    flash('Signed out', 'success')
    return redirect(url_for('blog.index'))

blog/views/blog.py
from flask import Blueprint
from blog.extensions import db
from blog.models import Article, Category, Comment, Bio, Skill, Project, Work_
from blog.forms import comment_form, admin_comment_form
from flask import render_template, flash, redirect, url_for
from flask import request, current_app
from blog.emails import send_reply_comment, send_new_comment_reminding

from flask_login import current_user
from blog.views.management import redirect_to_last_page

blog_blueprint = Blueprint('blog', __name__)

@blog_blueprint.route('/')
def index():
    return render_template('blog/index.html')


@blog_blueprint.route('/recommend')
def recommend():
    page = request.args.get('page', 1, type = int)
    per_page = current_app.config['ARTICLE_PER_PAGE']
    
    pagination = Article.query.order_by(Article.count_read.desc()).paginate(page, per_page = per_page)
    articles = pagination.items
    return render_template('blog/recommend.html', pagination = pagination, articles = articles)

@blog_blueprint.route('/display')
def display():
    page = request.args.get('page', 1, type = int)
    per_page = current_app.config['ARTICLE_PER_PAGE']
    pagination = Article.query.order_by(Article.timestamp.desc()).paginate(page, per_page = per_page)
    articles = pagination.items
    return render_template('blog/display.html', pagination = pagination, articles = articles)

@blog_blueprint.route('/about')
def about():
    bio = Bio.query.first()
    works = Work_.query.all()
    projects = Project.query.all()
    skills = Skill.query.all()
    return render_template('blog/bio.html', bio=bio, works=works, projects=projects, skills=skills)



@blog_blueprint.route('/article/<int:article_id>', methods=['GET', 'POST'])
def display_article(article_id):
    article = Article.query.get_or_404(article_id)
    article.count_read = article.count_read + 1
    db.session.commit()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MANAGE_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(article).filter_by(
        reviewed = True).order_by(Comment.timestamp.asc()).paginate(page, per_page)
    comments = pagination.items
    
    if current_user.is_authenticated:
        form = admin_comment_form()
        form.person_post.data = current_user.name
        form.email.data = current_app.config['MAIL_USERNAME']
        from_admin = True
        reviewed = True 
        form.site.data = url_for('.index')
    else:
        form = comment_form()
        from_admin = False
        reviewed = False

    if form.validate_on_submit():
        person_post = form.person_post.data 
        email = form.email.data    
        body = form.body.data 
        site = form.site.data 
        comment = Comment(
            person_post=person_post,
            email=email,
            site=site,
            body=body,           
            article=article,
            from_admin=from_admin,
            reviewed=reviewed
        )
        reply_id = request.args.get('reply')
        if reply_id:
            replied_comment = Comment.query.get_or_404(reply_id)
            comment.replied = replied_comment
            send_reply_comment(replied_comment)
        db.session.add(comment)
        db.session.commit()

        if current_user.is_authenticated:
            flash('Displayed', 'success')
        else:
            flash('Will display after being accepted', 'success')
            send_new_comment_reminding(article)
        return redirect(url_for('.display_article', article_id=article_id))
    return render_template('blog/article.html', article=article, 
                                                pagination=pagination, 
                                                form=form, 
                                                comments=comments)

@blog_blueprint.route('/reply/comment/<int:comment_id>')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if not comment.article.comment_open:
        flash('Cannot comment this article')
        return redirect(url_for('.display_article', article_id=comment.article.id))
    return redirect( url_for('.display_article', article_id=comment.article_id, 
        reply=comment_id, person_post=comment.person_post) + '#comment-form')                                        
        


@blog_blueprint.route('/category/<int:category_id>')
def display_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ARTICLE_PER_PAGE']
    pagination = Article.query.with_parent(category).order_by(Article.timestamp.desc()).paginate(page, per_page)
    articles = pagination.items
    return render_template('blog/category.html', category=category, 
        pagination=pagination, articles=articles)

blog/views/management.py
import os
from flask import Blueprint, render_template, send_from_directory
from flask_login import login_user, logout_user
from flask_login import login_required, current_user
from blog.forms import bio_form, article_form, category_form, work_form, project_form, skill_form, bio_form
from blog.extensions import db
from flask_ckeditor import upload_success, upload_fail

from blog.models import Article, Category, Comment, Bio, Skill, Project, Work_
from flask import render_template, flash, redirect, url_for
from flask import  request, current_app

manage_blueprint = Blueprint('management', __name__)

try:
    from urlparse import urlparse, urljoin
except ImportError:
    from urllib.parse import urlparse, urljoin

def safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return test_url.scheme in ('http', 'https') and ref_url.netloc == test_url.netloc

def redirect_to_last_page(default = 'blog.index', **kwargs):
    for target in request.args.get('next'), request.referrer:
        if not target:
            continue
        if safe_url(target):
            return redirect(target)
    return redirect(url_for(default, **kwargs))

@manage_blueprint.route('/article/manage')
@login_required
def manage_article():
    page = request.args.get('page', 1, type=int)
    onepage = Article.query.order_by(
        Article.timestamp.desc()).paginate(
        page, per_page=current_app.config['MANAGE_ARTICLE_PER_PAGE'])
    onepage_articles = onepage.items
    return render_template('manage/manage_article.html', page=page, pagination=onepage, articles=onepage_articles)


@manage_blueprint.route('/article/<int:article_id>/edit', methods=['POST', 'GET'])
@login_required
def edit_article(article_id):
    form = article_form()
    article = Article.query.get_or_404(article_id)
    if form.validate_on_submit():
        article.title = form.title.data 
        article.body = form.body.data 
        article.post = Category.query.get(form.category.data)
        db.session.commit()
        flash('Updated', 'success')
        return redirect(url_for('blog.display_article', article_id=article.id))
    form.title.data = article.title
    form.body.data = article.body
    form.category.data = article.category_id
    return render_template('manage/edit_article.html', form=form)

@manage_blueprint.route('/article/<int:article_id>/delete', methods=['POST'])
@login_required
def delete_article(article_id):
    article = Article.query.get_or_404(article_id)
    db.session.delete(article)
    db.session.commit()
    flash('Deleted', 'success')
    return redirect_to_last_page()

@manage_blueprint.route('/category/manage')
@login_required
def manage_category():
    return render_template('manage/manage_categories.html')

@manage_blueprint.route('/bio/edit', methods=['POST', 'GET'])
@login_required
def edit_bio():
    form = bio_form()
    bio = Bio.query.first()
    if form.validate_on_submit():
        bio.name = form.name.data 
        bio.current_job =form.current_job.data     
        bio.intro = form.body.data
        db.session.commit()
        flash('Updated', 'success')
        return redirect(url_for('.manage_bio'))
    form.name.data = bio.name
    form.current_job.data = bio.current_job
    form.body.data = bio.intro
    return render_template('manage/edit_bio.html', form=form, title='Bio') 

@manage_blueprint.route('/bio/add', methods=['POST', 'GET'])
@login_required
def add_bio():
    form = bio_form()
    if form.validate_on_submit():
        bio.name = form.name.data 
        bio.current_job =form.current_job.dat 
        bio.intro = form.body.data
        db.session.commit()
        flash('Updated', 'success')
        return redirect_to_last_page()
    return render_template('manage/add_bio.html', form=form, title='Bio')

@manage_blueprint.route('/skill/<int:skill_id>/edit', methods=['POST', 'GET'])
@login_required
def edit_skill(skill_id):
    form = skill_form()
    skill = Skill.query.get(skill_id)
    if form.validate_on_submit():
        skill.content = form.content.data    
        skill.is_techical = form.techical.data     
        
        db.session.commit()
        flash('Edited', 'success')
        return redirect(url_for('.manage_bio'))
    form.content.data = skill.content
    form.techical.data = skill.is_techical
    return render_template('manage/edit_bio.html', form=form, title='Skill')

@manage_blueprint.route('/work/<int:work_id>/edit', methods=['POST', 'GET'])
@login_required
def edit_work(work_id):
    form = work_form()
    work = Work_.query.get(work_id)
    if form.validate_on_submit():
        work.title = form.title.data 
        work.company = form.company.data
        work.time = form.time.data   
        work.abstract = form.body.data   
        db.session.commit()
        flash('Edited', 'success')
        return redirect(url_for('.manage_bio'))
    form.title.data  = work.title
    form.company.data = work.company
    form.time.data = work.time
    form.body.data = work.abstract
    return render_template('manage/edit_bio.html', form=form, title='Work Experience')

@manage_blueprint.route('/project/<int:project_id>/edit', methods=['POST', 'GET'])
@login_required
def edit_project(project_id):
    form = project_form()
    project = Project.query.get(project_id)
    if form.validate_on_submit():
        project.title = form.title.data 
        project.role = form.role.data      
        project.abstract = form.body.data   
        
        db.session.commit()
        flash('Edited', 'success')
        return redirect(url_for('.manage_bio'))
    form.title.data = project.title
    form.role.data = project.role
    form.body.data = project.abstract

    return render_template('manage/edit_bio.html', form=form, title='Project')
    

@manage_blueprint.route('/skill/<int:skill_id>/delete', methods=['POST'])
@login_required
def delete_skill(skill_id):
    skill = Skill.query.get_or_404(skill_id)
    work.delete()
    flash('Deleted', 'success')
    return render_template('manage/manage_bio.html')

@manage_blueprint.route('/project/<int:project_id>/delete', methods=['POST'])
@login_required
def delete_project(project_id):
    project = Project.query.get_or_404(project_id)
    project.delete()
    flash('Deleted', 'success')
    return render_template('manage/manage_bio.html')

@manage_blueprint.route('/work/<int:work_id>/delete', methods=['POST'])
@login_required
def delete_work(work_id):
    work = Work_.query.get_or_404(work_id)
    work.delete()
    flash('Deleted', 'success')
    return render_template('manage/manage_bio.html')

@manage_blueprint.route('skill/<int:skill_id>/set_techical', methods=['POST'])
@login_required
def set_techical(skill_id):
    skill = Skill.query.get_or_404(skill_id)
    if skill.is_techical:
        skill.is_techical = False
    else:
        skill.is_techical = True
    db.session.commit()
    return redirect_to_last_page()

@manage_blueprint.route('/work/add', methods = ['GET', 'POST'])
@login_required
def add_work():
    form = work_form()
    if form.validate_on_submit():
        title = form.title.data 
        company = form.company.data
        time = form.time.data   
        abstract = form.body.data   
        work = Work_(title=title, company=company, time=time, abstract=abstract) 
        db.session.add(work)
        db.session.commit()
        flash('Added', 'success')
        return redirect(url_for('.manage_bio'))
    return render_template('manage/add_bio.html', form=form, title='Work Experience')
    

@manage_blueprint.route('/skill/add', methods = ['GET', 'POST'])
@login_required
def add_skill():
    form = skill_form()
    if form.validate_on_submit():
        content = form.content.data    
        is_techical = form.techical.data     
        skill = Skill(content=content) 
        db.session.add(skill)
        db.session.commit()
        flash('Added', 'success')
        return redirect(url_for('.manage_bio'))
    return render_template('manage/add_bio.html', form=form, title='Skill')

@manage_blueprint.route('/project/add', methods = ['GET', 'POST'])
@login_required
def add_project():
    form = project_form()
    if form.validate_on_submit():
        title = form.title.data 
        role = form.role.data      
        abstract = form.body.data   
        project = Project(title=title, role=role, abstract=abstract) 
        db.session.add(project)
        db.session.commit()
        flash('Added', 'success')
        return redirect(url_for('.manage_bio'))
    return render_template('manage/add_bio.html', form=form, title='Project')



@manage_blueprint.route('/bio/manage')
@login_required
def manage_bio():
    bio = Bio.query.first()
    works = Work_.query.all()
    projects = Project.query.all()
    skills = Skill.query.all()
    return render_template('manage/manage_bio.html', bio=bio, works=works, projects=projects, skills=skills)

@manage_blueprint.route('/category/<int:category_id>/delete', methods=['POST'])
@login_required
def delete_category(category_id):
    category = Category.query.get_or_404(category_id)
    if category.id == 1:
        flash('This is a default category! Cannot delete!', 'warning')
        return render_template('manage/manage_categories.html')
    category.delete()
    flash('Deleted', 'success')
    return render_template('manage/manage_categories.html')

@manage_blueprint.route('/article/add', methods = ['GET', 'POST'])
@login_required
def add_article():
    form = article_form()
    if form.validate_on_submit():
        title = form.title.data 
        body = form.body.data 
        category = Category.query.get(form.category.data)    
        article = Article(title=title, body=body, category=category, count_read=0)
        db.session.add(article)
        db.session.commit()
        flash('Added', 'success')
        return redirect(url_for('blog.display_article', article_id=article.id))
    return render_template('manage/add_article.html', form=form)

blog/templates/layout.html
{% from 'bootstrap/nav.html' import render_nav_item %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% block head%}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        {% block title %}
        {% endblock title%} - {{admin.blog_title | default('Blog Title')}}
    </title>

    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
    
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" type="text/css">
   
    {% endblock head%}
</head>

<body>
    {% block nav%}
    <nav class="navbar navbar-expand-lg navbar-primary bg-light">
        <div class="container">
            <a class="navbar-brand text-uppercase" style="font-weight: bold;" href="{{ url_for('blog.index')}}" >
                {{ admin.name}}
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03"
                aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation" >
                <span class="navbar-toggler-icon" style="color: #4582ec; font-weight: bold;">MENU</span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor03">
                <ul class="navbar-nav mr-auto text-uppercase">
                    <li class="nav-item">
                        <a class="nav-link" style="font-weight: bold;" href="{{ url_for('blog.index')}}" >
                            Home
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" style="font-weight: bold;" href="{{ url_for('blog.about')}}" >
                            About
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" style="font-weight: bold;" href="{{ url_for('blog.recommend')}}" >
                            recommend
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" style="font-weight: bold;" href="{{ url_for('blog.display')}}" >
                            BLog
                        </a>
                    </li>
                
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle text-uppercase" data-toggle="dropdown" role="button"
                            aria-haspopup="true" aria-expanded="false" style="font-weight: bold;">
                            Management
                            <span class="caret"></span>
                            {% if unread_comments %}
                            <span class="badge badge-success">
                                new
                            </span>
                            {% endif %}
                        </a>
                        <div class="dropdown-menu ">
                            <a class="dropdown-item" href="{{ url_for('management.add_article') }}" style="font-weight: bold;">
                                New Article
                            </a>
                            <a class="dropdown-item" href="{{ url_for('management.add_category') }}" style="font-weight: bold;">
                                New Category
                            </a>
                            <a class="dropdown-item" href="{{ url_for('management.manage_article') }}" style="font-weight: bold;">
                                Manage Article
                            </a>
                            <a class="dropdown-item" href="{{ url_for('management.manage_category') }}" style="font-weight: bold;">
                                Manage Category
                            </a>
                            <a class="dropdown-item" href="{{ url_for('management.manage_comment') }}" style="font-weight: bold;">
                                Manage Comment
                                {% if unread_comments %}
                                    <span class="badge badge-success"> 
                                        {{ unread_comments }}
                                    </span>
                                {% endif %}
                            </a>
                            <a class="dropdown-item" href="{{ url_for('management.manage_bio') }}" style="font-weight: bold;">
                                Manage AboutMe
                            </a>
                            <a class="dropdown-item" href="{{ url_for('authorization.logout', next = request.full_path )}}" 
                            style="font-weight: bold;" >
                                Logout
                            </a>
                            {% else %}
                            <li  class="nav-item">
                                <a class="nav-link" href="{{ url_for('authorization.login', next = request.full_path )}}"
                                style="font-weight: bold;" >
                                    Login
                                </a>
                            </li>
                            {% endif %}
                        </div>
                    </li>
                </ul>

            </div>
        </div>
    </nav>
    {% endblock nav %}

    <main class="container">
        {% for message in get_flashed_messages(with_categories=True) %}
        <div class="alert alert-{{ message[0] }}" role="alert">
            <button type="button" class="close" data-dismiss="alert">
                &times;
            </button>
            {{ message[1] }}
        </div>
        {% endfor %}
        {% block content %}
        {% endblock content %}
        {% block footer %}
        <footer>
            <p class="float-left">
                <small>
                    &copy; 2020 Junhao & Yihua
                </small>
            </p>
        </footer>
        {% endblock footer %}
    </main>

    {% block script %}
    <script type="text/javascript" src="{{ url_for('static', filename = 'js/jquery-3.2.1.slim.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename = 'js/popper.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename = 'js/bootstrap.min.js') }}"></script>
    <script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>

    <script type="text/javascript" src="{{ url_for('static', filename = 'js/script.js') }}"></script>
    {% endblock %}
</body>

</html>