blog/views/blog.py
from flask import Blueprint
from blog.extensions import db
from blog.models import Article, Category, Comment, Bio, Skill, Project, Work_
from blog.forms import comment_form, admin_comment_form
from flask import render_template, flash, redirect, url_for
from flask import request, current_app
from blog.emails import send_reply_comment, send_new_comment_reminding

from flask_login import current_user
from blog.views.management import redirect_to_last_page

blog_blueprint = Blueprint('blog', __name__)

@blog_blueprint.route('/')
def index():
    return render_template('blog/index.html')


@blog_blueprint.route('/recommend')
def recommend():
    page = request.args.get('page', 1, type = int)
    per_page = current_app.config['ARTICLE_PER_PAGE']
    
    pagination = Article.query.order_by(Article.count_read.desc()).paginate(page, per_page = per_page)
    articles = pagination.items
    return render_template('blog/recommend.html', pagination = pagination, articles = articles)

@blog_blueprint.route('/display')
def display():
    page = request.args.get('page', 1, type = int)
    per_page = current_app.config['ARTICLE_PER_PAGE']
    pagination = Article.query.order_by(Article.timestamp.desc()).paginate(page, per_page = per_page)
    articles = pagination.items
    return render_template('blog/display.html', pagination = pagination, articles = articles)

@blog_blueprint.route('/about')
def about():
    bio = Bio.query.first()
    works = Work_.query.all()
    projects = Project.query.all()
    skills = Skill.query.all()
    return render_template('blog/bio.html', bio=bio, works=works, projects=projects, skills=skills)



@blog_blueprint.route('/article/<int:article_id>', methods=['GET', 'POST'])
def display_article(article_id):
    article = Article.query.get_or_404(article_id)
    article.count_read = article.count_read + 1
    db.session.commit()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MANAGE_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(article).filter_by(
        reviewed = True).order_by(Comment.timestamp.asc()).paginate(page, per_page)
    comments = pagination.items
    
    if current_user.is_authenticated:
        form = admin_comment_form()
        form.person_post.data = current_user.name
        form.email.data = current_app.config['MAIL_USERNAME']
        from_admin = True
        reviewed = True 
        form.site.data = url_for('.index')
    else:
        form = comment_form()
        from_admin = False
        reviewed = False

    if form.validate_on_submit():
        person_post = form.person_post.data 
        email = form.email.data    
        body = form.body.data 
        site = form.site.data 
        comment = Comment(
            person_post=person_post,
            email=email,
            site=site,
            body=body,           
            article=article,
            from_admin=from_admin,
            reviewed=reviewed
        )
        reply_id = request.args.get('reply')
        if reply_id:
            replied_comment = Comment.query.get_or_404(reply_id)
            comment.replied = replied_comment
            send_reply_comment(replied_comment)
        db.session.add(comment)
        db.session.commit()

        if current_user.is_authenticated:
            flash('Displayed', 'success')
        else:
            flash('Will display after being accepted', 'success')
            send_new_comment_reminding(article)
        return redirect(url_for('.display_article', article_id=article_id))
    return render_template('blog/article.html', article=article, 
                                                pagination=pagination, 
                                                form=form, 
                                                comments=comments)

@blog_blueprint.route('/reply/comment/<int:comment_id>')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if not comment.article.comment_open:
        flash('Cannot comment this article')
        return redirect(url_for('.display_article', article_id=comment.article.id))
    return redirect( url_for('.display_article', article_id=comment.article_id, 
        reply=comment_id, person_post=comment.person_post) + '#comment-form')                                        
        


@blog_blueprint.route('/category/<int:category_id>')
def display_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ARTICLE_PER_PAGE']
    pagination = Article.query.with_parent(category).order_by(Article.timestamp.desc()).paginate(page, per_page)
    articles = pagination.items
    return render_template('blog/category.html', category=category, 
        pagination=pagination, articles=articles)

blog/views/management.py
import os
from flask import Blueprint, render_template, send_from_directory
from flask_login import login_user, logout_user
from flask_login import login_required, current_user
from blog.forms import bio_form, article_form, category_form, work_form, project_form, skill_form, bio_form
from blog.extensions import db
from flask_ckeditor import upload_success, upload_fail

from blog.models import Article, Category, Comment, Bio, Skill, Project, Work_
from flask import render_template, flash, redirect, url_for
from flask import  request, current_app

manage_blueprint = Blueprint('management', __name__)

try:
    from urlparse import urlparse, urljoin
except ImportError:
    from urllib.parse import urlparse, urljoin

def safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return test_url.scheme in ('http', 'https') and ref_url.netloc == test_url.netloc

def redirect_to_last_page(default = 'blog.index', **kwargs):
    for target in request.args.get('next'), request.referrer:
        if not target:
            continue
        if safe_url(target):
            return redirect(target)
    return redirect(url_for(default, **kwargs))

@manage_blueprint.route('/article/manage')
@login_required
def manage_article():
    page = request.args.get('page', 1, type=int)
    onepage = Article.query.order_by(
        Article.timestamp.desc()).paginate(
        page, per_page=current_app.config['MANAGE_ARTICLE_PER_PAGE'])
    onepage_articles = onepage.items
    return render_template('manage/manage_article.html', page=page, pagination=onepage, articles=onepage_articles)


@manage_blueprint.route('/article/<int:article_id>/edit', methods=['POST', 'GET'])
@login_required
def edit_article(article_id):
    form = article_form()
    article = Article.query.get_or_404(article_id)
    if form.validate_on_submit():
        article.title = form.title.data 
        article.body = form.body.data 
        article.post = Category.query.get(form.category.data)
        db.session.commit()
        flash('Updated', 'success')
        return redirect(url_for('blog.display_article', article_id=article.id))
    form.title.data = article.title
    form.body.data = article.body
    form.category.data = article.category_id
    return render_template('manage/edit_article.html', form=form)

@manage_blueprint.route('/article/<int:article_id>/delete', methods=['POST'])
@login_required
def delete_article(article_id):
    article = Article.query.get_or_404(article_id)
    db.session.delete(article)
    db.session.commit()
    flash('Deleted', 'success')
    return redirect_to_last_page()

@manage_blueprint.route('/category/manage')
@login_required
def manage_category():
    return render_template('manage/manage_categories.html')

@manage_blueprint.route('/bio/edit', methods=['POST', 'GET'])
@login_required
def edit_bio():
    form = bio_form()
    bio = Bio.query.first()
    if form.validate_on_submit():
        bio.name = form.name.data 
        bio.current_job =form.current_job.data     
        bio.intro = form.body.data
        db.session.commit()
        flash('Updated', 'success')
        return redirect(url_for('.manage_bio'))
    form.name.data = bio.name
    form.current_job.data = bio.current_job
    form.body.data = bio.intro
    return render_template('manage/edit_bio.html', form=form, title='Bio') 

@manage_blueprint.route('/bio/add', methods=['POST', 'GET'])
@login_required
def add_bio():
    form = bio_form()
    if form.validate_on_submit():
        bio.name = form.name.data 
        bio.current_job =form.current_job.dat 
        bio.intro = form.body.data
        db.session.commit()
        flash('Updated', 'success')
        return redirect_to_last_page()
    return render_template('manage/add_bio.html', form=form, title='Bio')

@manage_blueprint.route('/skill/<int:skill_id>/edit', methods=['POST', 'GET'])
@login_required
def edit_skill(skill_id):
    form = skill_form()
    skill = Skill.query.get(skill_id)
    if form.validate_on_submit():
        skill.content = form.content.data    
        skill.is_techical = form.techical.data     
        
        db.session.commit()
        flash('Edited', 'success')
        return redirect(url_for('.manage_bio'))
    form.content.data = skill.content
    form.techical.data = skill.is_techical
    return render_template('manage/edit_bio.html', form=form, title='Skill')

@manage_blueprint.route('/work/<int:work_id>/edit', methods=['POST', 'GET'])
@login_required
def edit_work(work_id):
    form = work_form()
    work = Work_.query.get(work_id)
    if form.validate_on_submit():
        work.title = form.title.data 
        work.company = form.company.data
        work.time = form.time.data   
        work.abstract = form.body.data   
        db.session.commit()
        flash('Edited', 'success')
        return redirect(url_for('.manage_bio'))
    form.title.data  = work.title
    form.company.data = work.company
    form.time.data = work.time
    form.body.data = work.abstract
    return render_template('manage/edit_bio.html', form=form, title='Work Experience')

@manage_blueprint.route('/project/<int:project_id>/edit', methods=['POST', 'GET'])
@login_required
def edit_project(project_id):
    form = project_form()
    project = Project.query.get(project_id)
    if form.validate_on_submit():
        project.title = form.title.data 
        project.role = form.role.data      
        project.abstract = form.body.data   
        
        db.session.commit()
        flash('Edited', 'success')
        return redirect(url_for('.manage_bio'))
    form.title.data = project.title
    form.role.data = project.role
    form.body.data = project.abstract

    return render_template('manage/edit_bio.html', form=form, title='Project')
    

@manage_blueprint.route('/skill/<int:skill_id>/delete', methods=['POST'])
@login_required
def delete_skill(skill_id):
    skill = Skill.query.get_or_404(skill_id)
    work.delete()
    flash('Deleted', 'success')
    return render_template('manage/manage_bio.html')

@manage_blueprint.route('/project/<int:project_id>/delete', methods=['POST'])
@login_required
def delete_project(project_id):
    project = Project.query.get_or_404(project_id)
    project.delete()
    flash('Deleted', 'success')
    return render_template('manage/manage_bio.html')

@manage_blueprint.route('/work/<int:work_id>/delete', methods=['POST'])
@login_required
def delete_work(work_id):
    work = Work_.query.get_or_404(work_id)
    work.delete()
    flash('Deleted', 'success')
    return render_template('manage/manage_bio.html')

@manage_blueprint.route('skill/<int:skill_id>/set_techical', methods=['POST'])
@login_required
def set_techical(skill_id):
    skill = Skill.query.get_or_404(skill_id)
    if skill.is_techical:
        skill.is_techical = False
    else:
        skill.is_techical = True
    db.session.commit()
    return redirect_to_last_page()

@manage_blueprint.route('/work/add', methods = ['GET', 'POST'])
@login_required
def add_work():
    form = work_form()
    if form.validate_on_submit():
        title = form.title.data 
        company = form.company.data
        time = form.time.data   
        abstract = form.body.data   
        work = Work_(title=title, company=company, time=time, abstract=abstract) 
        db.session.add(work)
        db.session.commit()
        flash('Added', 'success')
        return redirect(url_for('.manage_bio'))
    return render_template('manage/add_bio.html', form=form, title='Work Experience')
    

@manage_blueprint.route('/skill/add', methods = ['GET', 'POST'])
@login_required
def add_skill():
    form = skill_form()
    if form.validate_on_submit():
        content = form.content.data    
        is_techical = form.techical.data     
        skill = Skill(content=content) 
        db.session.add(skill)
        db.session.commit()
        flash('Added', 'success')
        return redirect(url_for('.manage_bio'))
    return render_template('manage/add_bio.html', form=form, title='Skill')

@manage_blueprint.route('/project/add', methods = ['GET', 'POST'])
@login_required
def add_project():
    form = project_form()
    if form.validate_on_submit():
        title = form.title.data 
        role = form.role.data      
        abstract = form.body.data   
        project = Project(title=title, role=role, abstract=abstract) 
        db.session.add(project)
        db.session.commit()
        flash('Added', 'success')
        return redirect(url_for('.manage_bio'))
    return render_template('manage/add_bio.html', form=form, title='Project')



@manage_blueprint.route('/bio/manage')
@login_required
def manage_bio():
    bio = Bio.query.first()
    works = Work_.query.all()
    projects = Project.query.all()
    skills = Skill.query.all()
    return render_template('manage/manage_bio.html', bio=bio, works=works, projects=projects, skills=skills)

@manage_blueprint.route('/category/<int:category_id>/delete', methods=['POST'])
@login_required
def delete_category(category_id):
    category = Category.query.get_or_404(category_id)
    if category.id == 1:
        flash('This is a default category! Cannot delete!', 'warning')
        return render_template('manage/manage_categories.html')
    category.delete()
    flash('Deleted', 'success')
    return render_template('manage/manage_categories.html')

@manage_blueprint.route('/article/add', methods = ['GET', 'POST'])
@login_required
def add_article():
    form = article_form()
    if form.validate_on_submit():
        title = form.title.data 
        body = form.body.data 
        category = Category.query.get(form.category.data)    
        article = Article(title=title, body=body, category=category, count_read=0)
        db.session.add(article)
        db.session.commit()
        flash('Added', 'success')
        return redirect(url_for('blog.display_article', article_id=article.id))
    return render_template('manage/add_article.html', form=form)

blog/templates/blog/about.html
{% extends 'layout.html' %}

{% block title %}
    About
{% endblock %}
{% block content %}
<div class="page-header">
    <h1>About</h1>
</div>
<div class="row">
    <div class="col-sm-8">
        {{ admin.about | safe}}
    </div>
    <div class="col-sm-4 sidebar">
        {% if categories %}
            <div class="card mb-3">
                <div class="card-header">
                    Categories
                </div>
                <ul class="list-group list-group-flush">
                    {% for category in categories %}
                        <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                            <a href="{{ url_for('blog.display_category', category_id = category.id) }}">
                                {{ category.name}}
                            </a>
                            <span class="badge badge-primary badge-pill">
                                {{ category.articles | length }}
                            </span>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

blog/templates/blog/article.html
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'bootstrap/form.html' import render_form %}
{% extends 'layout.html' %}

{% block title %}
{{ article.title}}
{% endblock %}
{% block content %}
<div class="page-header">
    <h1>
        <p></p>
        {{article.title}}
    </h1>
    <ul class="float-right">
        {% if current_user.is_authenticated %}
        <a class="btn btn-link" href="{{url_for('management.edit_article', article_id = article.id)}}">
            Edit
        </a>
        <form class="inline" method="POST"
            action="{{ url_for('management.delete_article', article_id = article.id, next = url_for('blog.index'))}}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <button type="submit" class="btn btn-link"
                onclick="return confirm('Do you really want to delete this article?');">
                Delete
            </button>
        </form>
        {% endif %}
        <button type="button" class="btn btn-link" data-toggle="modal" data-target=".articleLinkModal">
            Share
        </button>
        <div class="modal fade articleLinkModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
            aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLable">
                            Copy to clipboard:
                        </h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">
                                &times;
                            </span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form=group">
                            <input type="text" class="form-control"
                                value="{{ url_for('.display_article', article_id = article.id, _external = True)}}"
                                readonly>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </ul>

    <div>
        <p></p>
        Category:&nbsp;
        <a href="{{ url_for('.display_category', category_id = article.category.id)}}">
            {{ article.category.name}}
        </a><br>
        Create Time:&nbsp;{{ article.timestamp}}
        <br>
        PageView:&nbsp;{{article.count_read}}
        <p></p>
        <br>
        <hr>

    </div>
</div>

<div class="row">
    <div class="col-sm-8">
        {{ article.body | safe}}

        <hr>
        <div class="comments" id="comments">
            <h3>
                {{ pagination.total}} Comments
                <small>
                    <a
                        href="{{ url_for('.display_article', article_id = article.id, page = pagination.pages or 1)}}#comments">
                        latest
                    </a>
                </small>
                {% if current_user.is_authenticated %}
                <form class="float-right" method="POST"
                        action="{{ url_for('management.set_comment', article_id=article.id, next=request.full_path) }}">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                        <button type="submit" class="btn btn-primary " 
                                >
                            {% if article.comment_open %}
                                Disable
                            {% else %}
                                Enable
                            {% endif %}
                                Comment
                        </button>
                    </form>
                {% endif %}
            </h3>
            {% if comments %}
            <ul class="list-group">
                {% for comment in comments %}
                <li class="list-group-item list-group-item-action flex-column">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">
                            <a href="{% if comment.site %}{{ comment.site}}{% else %}#{% endif %}" target="_blank">
                                {% if comment.from_admin %}
                                {{ admin.name}}
                                {% else %}
                                {{ comment.person_post}}
                                {% endif %}
                            </a>
                            {% if comment.from_admin %}
                            <span class="badge badge-primary">
                                Author
                            </span>
                            {% endif %}
                            {% if comment.replied %}
                            <span class="badge badge-light">
                                Reply
                            </span>
                            {% endif %}
                        </h5>
                        <small data-toggle="tooltip" data-placement="top" data-delay="500"
                            data-timestamp="{{ comment.timestamp.strftime('%Y-%m-%dT%H:%M:%SZ')}}">
                            {{ comment.timestamp}}
                        </small>
                    </div>
                    {% if comment.replied %}
                    <p class="alert alert-dark reply-body">
                        {{ comment.replied.person_post }}: <br>
                        {{ comment.replied.body}}
                    </p>
                    {% endif %}
                    <p class="mb-1">{{comment.body}}</p>
                    <div class="float-right">
                        <a href="{{ url_for('.reply_comment', comment_id = comment.id)}}" class="btn btn-light btn-sm">
                            Reply
                        </a>
                        {% if current_user.is_authenticated %}
                        <a class="btn btn-light btn-sm" href="mailto:{{ comment.email}}">
                            Email
                        </a>
                        <form class="inline" method="POST"
                            action="{{ url_for('management.delete_comment', comment_id = comment.id, next = request.full_pat)}}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                            <button type="submit" class="btn btn-danger btn-sm"
                                onclick="return confirm('Do you really want to delete this comment?');">
                                Delete
                            </button>
                        </form>
                        {% endif %}
                    </div>
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <div class="tip">
                <h5>There are no comments yet.</h5>
            </div>
            {% endif %}
        </div>
        {% if comments %}
        {{ render_pagination(pagination, fragment = '#comments')}}
        {% endif %}
        {% if request.args.get('reply') %}
        <div class="alert alert-dark">
            Reply to <strong>
                {{ request.args.get('person_post')}}
            </strong>:
            <a href="{{ url_for('.display_article', article_id = article.id)}}" class="float-right">
                Cancel
            </a>
        </div>
        {% endif %}
        {% if article.comment_open %}
        <div id="comment-form">
            {{ render_form(form, action = request.full_path)}}
        </div>
        {% else %}
        <div class="tip">
            <h5>The administrator has not opened comments area.</h5>
        </div>
        {% endif %}
    </div>
    <div class="col-sm-4 sidebar">
        {% if categories %}
        <div class="card mb-3">
            <div class="card-header">
                Categories
            </div>
            <ul class="list-group list-group-flush">
                {% for category in categories %}
                <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                    <a href="{{ url_for('blog.display_category', category_id = category.id) }}">
                        {{ category.name}}
                    </a>
                    <span class="badge badge-primary badge-pill">
                        {{ category.articles | length }}
                    </span>
                </li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

blog/templates/blog/category.html
{% from 'bootstrap/pagination.html' import render_pagination %}
{% extends 'layout.html' %}

{% block title %}
    {{ category.name}}
{% endblock %}
{% block content %}
    <div class="page-header">
        <h1>
            <p></p>
            Category -- {{ category.name}}
        </h1>
        <p class="text-muted">
            {{ category.articles | length}} articles
        </p>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {% if articles %}
                {% for article in articles %}
                    <h3 class="text-primary">
                        <a href="{{ url_for('.display_article', article_id = article.id)}}">
                            {{ article.title }}
                        </a>
                    </h3>
                    <p>
                        {{ article.body | striptags | truncate}}
                        <small>
                            <a href=" {{ url_for('.display_article', article_id = article.id) }}">
                                Read more
                            </a>
                        </small>
                    </p>
                    <small>
                        Comments: 
                        <a href="{{ url_for('.display_article', article_id = article.id)}}#comments">
                            {{ article.comments | length}}
                        </a>&nbsp;&nbsp;
                        Category: 
                        <a href="{{ url_for('.display_category', category_id = article.category.id)}}">
                                {{ article.category.name}}
                        </a>
                            <span class="float-right">
                                {{ article.timestamp}}
                            </span>
                    </small>
                    {% if not loop.last %}
                        <hr>
                    {% endif %}
                {% endfor %}
            {% else %}
                <div class="tip">
                    <h5>There are no articles yet.</h5>
                    {% if current_user.is_authenticated %}
                        <a href="{{ url_for('management.add_article')}}">
                            Write the first article
                        </a>
                    {% endif %}
                </div>
            {% endif %}
            <div class="page-footer">
                {{ render_pagination(pagination)}}
            </div>
        </div>
        <div class="col-sm-4 sidebar">
            {% if categories %}
            <div class="card mb-3">
                <div class="card-header">
                    Categories
                </div>
                <ul class="list-group list-group-flush">
                    {% for category in categories %}
                        <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                            <a href="{{ url_for('blog.display_category', category_id = category.id) }}">
                                {{ category.name}}
                            </a>
                            <span class="badge badge-primary badge-pill">
                                {{ category.articles | length }}
                            </span>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/display.html
{% from 'bootstrap/pagination.html' import render_pagination %}
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}
{% block content %}
    <div class="page-header">
        <br>
        <h2 >
            {{ admin.site_title | default('Blog Title')}}
            
        </h2>
        <br>
    </div>
    <div class="row">
        <div class="col-sm-8">
            
            {% if articles %}
                {% for article in articles %}
                    <h3 class="text-primary">
                        <a href="{{ url_for('.display_article', article_id = article.id)}}">
                            {{ article.title }}
                        </a>
                    </h3>
                    <p>
                        {{ article.body | striptags | truncate}}
                        <small>
                            <a href=" {{ url_for('.display_article', article_id = article.id) }}">
                                Read more
                            </a>
                        </small>
                    </p>
                    <small>
                        Comments:
                        <a href="{{ url_for('.display_article', article_id = article.id)}}#comments">
                            {{ article.comments | length}}
                        </a>&nbsp;&nbsp;
                        Category: 
                        <a href="{{ url_for('.display_category', category_id = article.category.id)}}">
                            {{ article.category.name}}
                        </a>
                        &nbsp;&nbsp;PageView:&nbsp;{{article.count_read}}
                            <span class="float-right">
                                {{ article.timestamp}}
                            </span>
                    </small>
                    {% if not loop.last %}
                        <hr>
                    {% endif %}
                {% endfor %}
            {% else %}
                <div class="tip">
                    <h5>There are no articles yet.</h5>
                    {% if current_user.is_authenticated %}
                        <a href="{{ url_for('management.add_article')}}">
                            Write the first article
                        </a>
                    {% endif %}
                </div>
            {% endif %}

            {% if articles %}
                <div class="page-footer">
                    {{ render_pagination(pagination)}}
                </div>
            {% endif %}
        </div>
        <div class="col-sm-4 sidebar">
            {% if categories %}
            <div class="card mb-3">
                <div class="card-header">
                    Categories
                </div>
                <ul class="list-group list-group-flush">
                    {% for category in categories %}
                        <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                            <a href="{{ url_for('blog.display_category', category_id = category.id) }}">
                                {{ category.name}}
                            </a>
                            <span class="badge badge-primary badge-pill">
                                {{ category.articles | length }}
                            </span>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        </div>
    </div>
{% endblock %}